### ISSUE TITLE
Security issue: Cryptography.InsecureAlgorithm "SHA1" on MessageDigest

### ISSUE THREAD

**Issue by GabrieleBarboni** [ibmruntimes/openj9-openjdk-jdk21#183]
Our product security scan has found a security issue related to Cryptography.InsecureAlgorithm (https://cwe.mitre.org/data/definitions/327) since MessageDigest is using "SHA1" as digest algorithm.
Is there any way to configure which algorithm to use for MessageDigest when loading PKCS12KeyStore?
It should use as per our investigation DEFAULT_MAC_ALGORITHM (HmacPBESHA256) instead it is using legacy one LEGACY_MAC_ALGORITHM (HmacPBESHA1) even if no legacy property has been set (keystore.pkcs12.legacy).

Stack trace:
java.security.MessageDigest.getInstance(MessageDigest.java:200)
com.sun.crypto.provider.HmacCore.<init>(HmacCore.java:77)
com.sun.crypto.provider.HmacPKCS12PBECore.<init>(HmacPKCS12PBECore.java:94)
com.sun.crypto.provider.HmacPKCS12PBECore$HmacPKCS12PBE_SHA1.<init>(HmacPKCS12P
BECore.java:47)
java.security.Provider$Service.newInstanceOf(Provider.java:1950)
java.security.Provider$Service.newInstanceUtil(Provider.java:1957)
java.security.Provider$Service.newInstance(Provider.java:1932)
javax.crypto.Mac.chooseProvider(Mac.java:364)
javax.crypto.Mac.init(Mac.java:464)
sun.security.pkcs12.PKCS12KeyStore.lambda$engineLoad$2(PKCS12KeyStore.java:2143)
sun.security.pkcs12.PKCS12KeyStore$RetryWithZero.run(PKCS12KeyStore.java:257)
sun.security.pkcs12.PKCS12KeyStore.engineLoad(PKCS12KeyStore.java:2140)
sun.security.util.KeyStoreDelegator.engineLoad(KeyStoreDelegator.java:228)
java.security.KeyStore.load(KeyStore.java:1500)

**Comment by pshipton** [comment]
@jasonkatonica can someone pls take a look to answer the question.

**Comment by jasonkatonica** [comment]
When loading a PKCS12 file a combination of crypto algorithms are used. The algorithms that are in use when loading the file are determined by the file itself. Could you describe further how the PKCS12 file was created, instead of how it was loaded? Some tooling allows for users to determine the cryptography used to create the file at the time that the file is created.

**Comment by GabrieleBarboni** [comment]
Hi,
thanks for your answer. We checked from our side after your input and we found out we are actually using wrong algorithms when creating PKCS12 file. Closing issue here, we will resolve internally. Thanks!
